name: CI Pipeline

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  packages: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 1. Checkout the code
        uses: actions/checkout@v4

      - name: 2. Set up Python
        uses: actions/setup-python@v5
        with: 
          python-version: "3.12"
      
      - name: 3. Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: 4. Run the tests
        env:
          API_KEY: "good_key"
        run: |
          pytest

      - name: 5. Log in to GHCR (GitHub Container Registry)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: 6. Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ghcr.io/chungchehsiao-tech/python-fastapi-data-ingestion-simulation:latest

